### ISSUE TITLE
TypeInitializationException when running SignIn with Starcounter 2.3.5364

### ISSUE THREAD

**Issue by Mackiovello** [StarcounterPrefabs/SignIn#56]
### Steps to reproduce

1. Download starcounter 2.3.0.5364
2. Start SignIn
3. Start Launcher
4. Go to localhost:8080/launcher

### Expected result
Launcher starts with signIn app

### Actual result
I get the error:
```
System.TypeInitializationException: The type initializer for 'SignIn.SessionContainer' threw an exception.
   at SignIn.SessionContainer..ctor()
   at SignIn.MainHandlers.GetSessionContainer() in C:\Users\Mackiovello\StarApps\SignIn\src\SignIn\Api\MainHandlers.cs:line 204
   at SignIn.MainHandlers.<Register>b__2_1() in C:\Users\Mackiovello\StarApps\SignIn\src\SignIn\Api\MainHandlers.cs:line 56
   at Starcounter.Rest.UserHandlerInfo.RunUserDelegate(Request req, IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack) in C:\TeamCity\BuildAgent\work\sc-183\Level1\src\Starcounter.Rest\UriHandlersManager.cs:line 221
   at Starcounter.Internal.Web.AppRestServer.RunDelegateAndProcessResponse(IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack, Request req) in C:\TeamCity\BuildAgent\work\sc-183\Level1\src\Starcounter.Apps.JsonPatch\AppRestServer.cs:line 98
   at Starcounter.Rest.UriManagedHandlersCodegen.RunUriMatcherAndCallHandler(String methodSpaceUriSpace, String methodSpaceUriSpaceLower, Request req, UInt16 portNumber, Response& resp) in C:\TeamCity\BuildAgent\work\sc-183\Level1\src\Starcounter.Rest\UriManagedHandlersCodegen.cs:line 1117
   at Starcounter.Self.DoSelfCall(UInt16 portNumber, String method, String relativeUri, Dictionary`2 headersDictionary, String body, Byte[] bodyBytes, HandlerOptions handlerOptions, Request req) in C:\TeamCity\BuildAgent\work\sc-183\Level1\src\Starcounter.Internal\Rest\Self.cs:line 397
   at Starcounter.UriMapping.MappingHandler(Request req, List`1 mappedHandlersList, String stringParam) in C:\TeamCity\BuildAgent\work\sc-183\Level1\src\Starcounter\Apps\OntologyAndOrdinaryMapping.cs:line 232
   at Starcounter.Rest.UserHandlerInfo.RunUserDelegate(Request req, IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack) in C:\TeamCity\BuildAgent\work\sc-183\Level1\src\Starcounter.Rest\UriHandlersManager.cs:line 161
   at Starcounter.Internal.Web.AppRestServer.RunDelegateAndProcessResponse(IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack, Request req) in C:\TeamCity\BuildAgent\work\sc-183\Level1\src\Starcounter.Apps.JsonPatch\AppRestServer.cs:line 98
   at Starcounter.Rest.UriManagedHandlersCodegen.RunUriMatcherAndCallHandler(String methodSpaceUriSpace, String methodSpaceUriSpaceLower, Request req, UInt16 portNumber, Response& resp) in C:\TeamCity\BuildAgent\work\sc-183\Level1\src\Starcounter.Rest\UriManagedHandlersCodegen.cs:line 1117
   at Starcounter.Self.DoSelfCall(UInt16 portNumber, String method, String relativeUri, Dictionary`2 headersDictionary, String body, Byte[] bodyBytes, HandlerOptions handlerOptions, Request req) in C:\TeamCity\BuildAgent\work\sc-183\Level1\src\Starcounter.Internal\Rest\Self.cs:line 397
   at Starcounter.Self.GET(String uri, Func`1 substituteHandler) in C:\TeamCity\BuildAgent\work\sc-183\Level1\src\Starcounter.Internal\Rest\Self.cs:line 90
   at Launcher.Helper.LauncherHelper.<>c.<Init>b__1_2(Request req) in C:\Users\Mackiovello\StarApps\Launcher\src\Launcher\Helper\LauncherHelper.cs:line 95
   at Starcounter.Rest.UserHandlerInfo.RunUserDelegate(Request req, IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack) in C:\TeamCity\BuildAgent\work\sc-183\Level1\src\Starcounter.Rest\UriHandlersManager.cs:line 221
   at Starcounter.Internal.Web.AppRestServer.RunDelegateAndProcessResponse(IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack, Request req) in C:\TeamCity\BuildAgent\work\sc-183\Level1\src\Starcounter.Apps.JsonPatch\AppRestServer.cs:line 98
   at Starcounter.Internal.AppsBootstrapper.ProcessExternalRequest(Request req) in C:\TeamCity\BuildAgent\work\sc-183\Level1\src\Starcounter.Apps.JsonPatch\AppsBootstrapper.cs:line 765
TypeName=SignIn.SessionContainer
HResult=-2146233036
---> System.MissingMethodException: Method not found: 'Void Starcounter.Templates.Template.set_ClassName(System.String)'.
   at SignIn.SessionContainer.JsonByExample.Schema..ctor()
   at SignIn.SessionContainer..cctor()
HResult=-2146233069
```
### Technical information

- Starcounter 2.3.0.5364
- SignIn app, both develop and master branch

Other apps work.
I've tried clearing the database.
The app worked on version 2.3.0.5358.

**Comment by chrhol** [comment]
This line:

> System.MissingMethodException: Method not found: 'Void Starcounter.Templates.Template.set_ClassName(System.String)'.

`Template.set_ClassName(System.String)` should not be called at all in 2.3 versions and it's really strange that it works in the earlier version of Starcounter, it was quite some time ago (1-2 months) since this was changed.

 We have had some problems on the buildserver where the wrong buildtask were used, maybe there is something wrong with the build. I will take a look at the build and see if I can see anything.

**Comment by chrhol** [comment]
The build looks correct, are you running the correct version of SignIn? The apps needs to be recompiled between 2.2 and 2.3 since the generated code is different.

**Comment by Mackiovello** [comment]
Huh, interesting. I downloaded and ran SignIn on 2.3 yesterday without a problem. Now I did a `git pull`, `./build.bat`, and `./run.bat` which made it work again.

Thank you, I'm closing the issue.
